# Generated by Django 2.2.6 on 2019-10-28 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_title', models.CharField(max_length=150, verbose_name='标题')),
                ('article_content', models.TextField(verbose_name='正文')),
                ('article_auth', models.CharField(max_length=20, verbose_name='作者')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('article_picurl', models.CharField(max_length=1000)),
            ],
        ),
    ]
