# Generated by Django 2.2.6 on 2019-11-27 15:49

from django.db import migrations
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_content',
            field=mdeditor.fields.MDTextField(),
        ),
    ]
