# Generated by Django 2.2.6 on 2019-10-28 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_picurl',
            field=models.ImageField(upload_to='upload/%Y/%m'),
        ),
    ]
