# Generated by Django 2.1.13 on 2019-10-30 05:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20191028_2048'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_top',
            field=models.BooleanField(default=False, verbose_name='置顶'),
        ),
        migrations.AlterField(
            model_name='article',
            name='article_column',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='blog.ArticleColumn'),
        ),
    ]
