# Generated by Django 2.1.13 on 2019-10-31 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20191030_1319'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ('-create_time',)},
        ),
    ]
